export const AVAILABLE_UNITS = [
  'Items',
  'Cups',
  'Tbsp',
  'Tsp',
  'Oz',
  'Fl Oz',
  'Lbs',
  'Grams',
  'Servings',
  'Bags',
  'Boxes',
  'Cans',
  'Jars',
  'Bottles',
  'Cartons',
  'Bunches',
  'Heads',
  'Cloves',
  'Loaves',
  'Dozen',
];
 
export const QUICK_ADDS = [
  { id: 'q1', icon: '🥛', name: 'Milk', category: 'Dairy / Refrigerated', unit: 'Cartons' },
  { id: 'q2', icon: '🥚', name: 'Eggs', category: 'Dairy / Refrigerated', unit: 'Items' },
  { id: 'q3', icon: '🧈', name: 'Butter', category: 'Dairy / Refrigerated', unit: 'Items' },
  { id: 'q4', icon: '🍗', name: 'Chicken Breast', category: 'Proteins', unit: 'Lbs' },
  { id: 'q5', icon: '🧅', name: 'Onions', category: 'Produce', unit: 'Items' },
  { id: 'q6', icon: '🧄', name: 'Garlic', category: 'Produce', unit: 'Cloves' },
  { id: 'q7', icon: '🍚', name: 'Rice', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { id: 'q8', icon: '🍝', name: 'Pasta', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { id: 'q9', icon: '🫒', name: 'Olive Oil', category: 'Condiments & Sauces', unit: 'Bottles' },
  { id: 'q10', icon: '🧂', name: 'Salt', category: 'Spices & Seasonings', unit: 'Items' },
  { id: 'q11', icon: '🍅', name: 'Tomatoes', category: 'Produce', unit: 'Items' },
  { id: 'q12', icon: '🧀', name: 'Cheddar Cheese', category: 'Dairy / Refrigerated', unit: 'Bags' },
];
 
export const SUGGESTION_LIBRARY = [
  // ============ PRODUCE ============
  { icon: '🧅', name: 'Onions', category: 'Produce', unit: 'Items' },
  { icon: '🧅', name: 'Red Onion', category: 'Produce', unit: 'Items' },
  { icon: '🧄', name: 'Garlic', category: 'Produce', unit: 'Cloves' },
  { icon: '🍅', name: 'Tomatoes', category: 'Produce', unit: 'Items' },
  { icon: '🍅', name: 'Cherry Tomatoes', category: 'Produce', unit: 'Cups' },
  { icon: '🥬', name: 'Lettuce', category: 'Produce', unit: 'Heads' },
  { icon: '🥬', name: 'Spinach', category: 'Produce', unit: 'Bags' },
  { icon: '🥬', name: 'Kale', category: 'Produce', unit: 'Bunches' },
  { icon: '🥦', name: 'Broccoli', category: 'Produce', unit: 'Heads' },
  { icon: '🥕', name: 'Carrots', category: 'Produce', unit: 'Items' },
  { icon: '🫑', name: 'Bell Peppers', category: 'Produce', unit: 'Items' },
  { icon: '🌶️', name: 'Jalapeños', category: 'Produce', unit: 'Items' },
  { icon: '🥒', name: 'Cucumber', category: 'Produce', unit: 'Items' },
  { icon: '🥒', name: 'Zucchini', category: 'Produce', unit: 'Items' },
  { icon: '🍄', name: 'Mushrooms', category: 'Produce', unit: 'Oz' },
  { icon: '🥔', name: 'Potatoes', category: 'Produce', unit: 'Lbs' },
  { icon: '🍠', name: 'Sweet Potatoes', category: 'Produce', unit: 'Items' },
  { icon: '🌽', name: 'Corn', category: 'Produce', unit: 'Items' },
  { icon: '🥑', name: 'Avocado', category: 'Produce', unit: 'Items' },
  { icon: '🌿', name: 'Celery', category: 'Produce', unit: 'Bunches' },
  { icon: '🌿', name: 'Green Onions', category: 'Produce', unit: 'Bunches' },
  { icon: '🌿', name: 'Cilantro', category: 'Produce', unit: 'Bunches' },
  { icon: '🌿', name: 'Parsley', category: 'Produce', unit: 'Bunches' },
  { icon: '🌿', name: 'Basil', category: 'Produce', unit: 'Bunches' },
  { icon: '🍋', name: 'Lemons', category: 'Produce', unit: 'Items' },
  { icon: '🍋', name: 'Limes', category: 'Produce', unit: 'Items' },
  { icon: '🍎', name: 'Apples', category: 'Produce', unit: 'Items' },
  { icon: '🍌', name: 'Bananas', category: 'Produce', unit: 'Items' },
  { icon: '🍓', name: 'Strawberries', category: 'Produce', unit: 'Bags' },
  { icon: '🫐', name: 'Blueberries', category: 'Produce', unit: 'Cups' },
  { icon: '🍇', name: 'Grapes', category: 'Produce', unit: 'Bags' },
  { icon: '🍊', name: 'Oranges', category: 'Produce', unit: 'Items' },
  { icon: '🍍', name: 'Pineapple', category: 'Produce', unit: 'Items' },
  { icon: '🫚', name: 'Ginger', category: 'Produce', unit: 'Oz' },
 
  // ============ PROTEINS ============
  { icon: '🍗', name: 'Chicken Breast', category: 'Proteins', unit: 'Lbs' },
  { icon: '🍗', name: 'Chicken Thighs', category: 'Proteins', unit: 'Lbs' },
  { icon: '🍗', name: 'Chicken Wings', category: 'Proteins', unit: 'Lbs' },
  { icon: '🍗', name: 'Rotisserie Chicken', category: 'Proteins', unit: 'Items' },
  { icon: '🥩', name: 'Ground Beef', category: 'Proteins', unit: 'Lbs' },
  { icon: '🥩', name: 'Steak', category: 'Proteins', unit: 'Lbs' },
  { icon: '🥩', name: 'Stew Beef', category: 'Proteins', unit: 'Lbs' },
  { icon: '🍖', name: 'Pork Chops', category: 'Proteins', unit: 'Lbs' },
  { icon: '🥓', name: 'Bacon', category: 'Proteins', unit: 'Oz' },
  { icon: '🌭', name: 'Sausage', category: 'Proteins', unit: 'Lbs' },
  { icon: '🦃', name: 'Ground Turkey', category: 'Proteins', unit: 'Lbs' },
  { icon: '🐟', name: 'Salmon', category: 'Proteins', unit: 'Lbs' },
  { icon: '🐟', name: 'Tilapia', category: 'Proteins', unit: 'Lbs' },
  { icon: '🐟', name: 'Canned Tuna', category: 'Proteins', unit: 'Cans' },
  { icon: '🍤', name: 'Shrimp', category: 'Proteins', unit: 'Lbs' },
  { icon: '🧊', name: 'Tofu', category: 'Proteins', unit: 'Items' },
  { icon: '🫘', name: 'Black Beans', category: 'Proteins', unit: 'Cans' },
  { icon: '🫘', name: 'Chickpeas', category: 'Proteins', unit: 'Cans' },
  { icon: '🫘', name: 'Kidney Beans', category: 'Proteins', unit: 'Cans' },
  { icon: '🫘', name: 'Lentils', category: 'Proteins', unit: 'Bags' },
 
  // ============ DAIRY / REFRIGERATED ============
  { icon: '🥛', name: 'Milk', category: 'Dairy / Refrigerated', unit: 'Cartons' },
  { icon: '🥛', name: 'Heavy Cream', category: 'Dairy / Refrigerated', unit: 'Cartons' },
  { icon: '🥛', name: 'Buttermilk', category: 'Dairy / Refrigerated', unit: 'Cartons' },
  { icon: '🥚', name: 'Eggs', category: 'Dairy / Refrigerated', unit: 'Items' },
  { icon: '🧈', name: 'Butter', category: 'Dairy / Refrigerated', unit: 'Items' },
  { icon: '🧀', name: 'Cheddar Cheese', category: 'Dairy / Refrigerated', unit: 'Bags' },
  { icon: '🧀', name: 'Mozzarella', category: 'Dairy / Refrigerated', unit: 'Bags' },
  { icon: '🧀', name: 'Parmesan', category: 'Dairy / Refrigerated', unit: 'Oz' },
  { icon: '🧀', name: 'Cream Cheese', category: 'Dairy / Refrigerated', unit: 'Items' },
  { icon: '🧀', name: 'Feta Cheese', category: 'Dairy / Refrigerated', unit: 'Oz' },
  { icon: '🥣', name: 'Greek Yogurt', category: 'Dairy / Refrigerated', unit: 'Items' },
  { icon: '🍦', name: 'Sour Cream', category: 'Dairy / Refrigerated', unit: 'Items' },
  { icon: '🥪', name: 'Mayonnaise', category: 'Dairy / Refrigerated', unit: 'Jars' },
 
  // ============ PANTRY / DRY GOODS ============
  { icon: '🍚', name: 'White Rice', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { icon: '🍚', name: 'Brown Rice', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { icon: '🍚', name: 'Jasmine Rice', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { icon: '🌾', name: 'Quinoa', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { icon: '🥣', name: 'Oats', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { icon: '🍝', name: 'Pasta', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { icon: '🍝', name: 'Spaghetti', category: 'Pantry / Dry Goods', unit: 'Boxes' },
  { icon: '🍜', name: 'Ramen Noodles', category: 'Pantry / Dry Goods', unit: 'Items' },
  { icon: '🍞', name: 'Bread', category: 'Pantry / Dry Goods', unit: 'Loaves' },
  { icon: '🫓', name: 'Tortillas', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { icon: '🥖', name: 'Flour', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { icon: '🍬', name: 'Sugar', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { icon: '🟤', name: 'Brown Sugar', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { icon: '🧁', name: 'Baking Powder', category: 'Pantry / Dry Goods', unit: 'Items' },
  { icon: '🧁', name: 'Baking Soda', category: 'Pantry / Dry Goods', unit: 'Items' },
  { icon: '🍫', name: 'Chocolate Cake Mix', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { icon: '🍪', name: 'Chocolate Chips', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { icon: '🥫', name: 'Canned Tomatoes', category: 'Pantry / Dry Goods', unit: 'Cans' },
  { icon: '🥫', name: 'Tomato Paste', category: 'Pantry / Dry Goods', unit: 'Cans' },
  { icon: '🥫', name: 'Coconut Milk', category: 'Pantry / Dry Goods', unit: 'Cans' },
  { icon: '🍲', name: 'Chicken Broth', category: 'Pantry / Dry Goods', unit: 'Cartons' },
  { icon: '🍲', name: 'Beef Broth', category: 'Pantry / Dry Goods', unit: 'Cartons' },
  { icon: '🥜', name: 'Peanut Butter', category: 'Pantry / Dry Goods', unit: 'Jars' },
  { icon: '🌰', name: 'Almonds', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { icon: '🥜', name: 'Walnuts', category: 'Pantry / Dry Goods', unit: 'Bags' },
  { icon: '🌻', name: 'Breadcrumbs', category: 'Pantry / Dry Goods', unit: 'Items' },
 
  // ============ CONDIMENTS & SAUCES ============
  { icon: '🫒', name: 'Olive Oil', category: 'Condiments & Sauces', unit: 'Bottles' },
  { icon: '🛢️', name: 'Vegetable Oil', category: 'Condiments & Sauces', unit: 'Bottles' },
  { icon: '🍶', name: 'Soy Sauce', category: 'Condiments & Sauces', unit: 'Bottles' },
  { icon: '🍯', name: 'Honey', category: 'Condiments & Sauces', unit: 'Jars' },
  { icon: '🧴', name: 'Vinegar', category: 'Condiments & Sauces', unit: 'Bottles' },
  { icon: '🧴', name: 'Balsamic Vinegar', category: 'Condiments & Sauces', unit: 'Bottles' },
  { icon: '🍅', name: 'Ketchup', category: 'Condiments & Sauces', unit: 'Bottles' },
  { icon: '🌭', name: 'Mustard', category: 'Condiments & Sauces', unit: 'Bottles' },
  { icon: '🌶️', name: 'Hot Sauce', category: 'Condiments & Sauces', unit: 'Bottles' },
  { icon: '🍝', name: 'Marinara Sauce', category: 'Condiments & Sauces', unit: 'Jars' },
  { icon: '🥗', name: 'Ranch Dressing', category: 'Condiments & Sauces', unit: 'Bottles' },
  { icon: '🍖', name: 'BBQ Sauce', category: 'Condiments & Sauces', unit: 'Bottles' },
  { icon: '🥫', name: 'Salsa', category: 'Condiments & Sauces', unit: 'Jars' },
  { icon: '🥜', name: 'Sesame Oil', category: 'Condiments & Sauces', unit: 'Bottles' },
  { icon: '🫙', name: 'Tahini', category: 'Condiments & Sauces', unit: 'Jars' },
 
  // ============ SPICES & SEASONINGS ============
  { icon: '🧂', name: 'Salt', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '⚫', name: 'Black Pepper', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🧄', name: 'Garlic Powder', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🧅', name: 'Onion Powder', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🌶️', name: 'Paprika', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🌶️', name: 'Chili Powder', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🌶️', name: 'Cayenne Pepper', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🟡', name: 'Cumin', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🟠', name: 'Turmeric', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🍂', name: 'Oregano', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🍂', name: 'Thyme', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🌿', name: 'Rosemary', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🍂', name: 'Italian Seasoning', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🟤', name: 'Cinnamon', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🤎', name: 'Vanilla Extract', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🍛', name: 'Curry Powder', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🌶️', name: 'Red Pepper Flakes', category: 'Spices & Seasonings', unit: 'Items' },
  { icon: '🍃', name: 'Bay Leaves', category: 'Spices & Seasonings', unit: 'Items' },
 
  // ============ FROZEN ============
  { icon: '🥦', name: 'Frozen Broccoli', category: 'Frozen', unit: 'Bags' },
  { icon: '🫛', name: 'Frozen Peas', category: 'Frozen', unit: 'Bags' },
  { icon: '🌽', name: 'Frozen Corn', category: 'Frozen', unit: 'Bags' },
  { icon: '🥬', name: 'Frozen Spinach', category: 'Frozen', unit: 'Bags' },
  { icon: '🫘', name: 'Edamame', category: 'Frozen', unit: 'Bags' },
  { icon: '🍓', name: 'Frozen Berries', category: 'Frozen', unit: 'Bags' },
  { icon: '🍟', name: 'Frozen Fries', category: 'Frozen', unit: 'Bags' },
  { icon: '🍤', name: 'Frozen Shrimp', category: 'Frozen', unit: 'Bags' },
  { icon: '🥟', name: 'Frozen Dumplings', category: 'Frozen', unit: 'Bags' },
  { icon: '🍕', name: 'Frozen Pizza', category: 'Frozen', unit: 'Items' },
];
 
export const INITIAL_CATEGORIES = [
  {
    id: 'c4',
    emoji: '🥦',
    category_name: 'Produce',
    count: 0,
    items: [],
  },
  {
    id: 'c1',
    emoji: '🥛',
    category_name: 'Dairy / Refrigerated',
    count: 3,
    items: [
      { id: 'i1', name: 'Eggs', quantity: 12, unit: 'Items' },
      { id: 'i2', name: 'Sour Cream', quantity: 1, unit: 'Items' },
      { id: 'i3', name: 'Butter', quantity: 4, unit: 'Items' },
    ],
  },
  {
    id: 'c3',
    emoji: '🥩',
    category_name: 'Proteins',
    count: 0,
    items: [],
  },
  {
    id: 'c2',
    emoji: '🥖',
    category_name: 'Pantry / Dry Goods',
    count: 2,
    items: [
      { id: 'i4', name: 'Chocolate Cake Mix', quantity: 2, unit: 'Bags' },
      { id: 'i5', name: 'Chocolate Chips', quantity: 1, unit: 'Bags' },
    ],
  },
  {
    id: 'c5',
    emoji: '🫒',
    category_name: 'Condiments & Sauces',
    count: 0,
    items: [],
  },
  {
    id: 'c6',
    emoji: '🧂',
    category_name: 'Spices & Seasonings',
    count: 0,
    items: [],
  },
  {
    id: 'c7',
    emoji: '🧊',
    category_name: 'Frozen',
    count: 0,
    items: [],
  },
];
 
export const MOCK_MEALS = [
  {
    id: 'm1',
    title: 'Creamy Garlic Chicken Pasta',
    matchPercentage: 92,
    usedIngredientsCount: 8,
    extraIngredientsRemaining: 4,
    tags: [
      { name: 'Chicken Breast', icon: '🍗' },
      { name: 'Pasta', icon: '🍝' },
      { name: 'Garlic', icon: '🧄' },
      { name: 'Heavy Cream', icon: '🥛' },
      { name: 'Parmesan', icon: '🧀' },
      { name: 'Butter', icon: '🧈' },
      { name: 'Onions', icon: '🧅' },
      { name: 'Black Pepper', icon: '⚫' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?q=80&w=300&auto=format&fit=crop',
  },
  {
    id: 'm2',
    title: 'Chicken & Veggie Rice Bowl',
    matchPercentage: 88,
    usedIngredientsCount: 8,
    extraIngredientsRemaining: 3,
    tags: [
      { name: 'Chicken Breast', icon: '🍗' },
      { name: 'Brown Rice', icon: '🍚' },
      { name: 'Broccoli', icon: '🥦' },
      { name: 'Carrots', icon: '🥕' },
      { name: 'Soy Sauce', icon: '🍶' },
      { name: 'Garlic', icon: '🧄' },
      { name: 'Sesame Oil', icon: '🥜' },
      { name: 'Green Onions', icon: '🌿' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=300&auto=format&fit=crop',
  },
  {
    id: 'm3',
    title: 'Cheesy Chicken Casserole',
    matchPercentage: 84,
    usedIngredientsCount: 7,
    extraIngredientsRemaining: 3,
    tags: [
      { name: 'Chicken Breast', icon: '🍗' },
      { name: 'Cheddar Cheese', icon: '🧀' },
      { name: 'Sour Cream', icon: '🍦' },
      { name: 'Onions', icon: '🧅' },
      { name: 'Chicken Broth', icon: '🍲' },
      { name: 'Breadcrumbs', icon: '🌻' },
      { name: 'Butter', icon: '🧈' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=300&auto=format&fit=crop',
  },
  {
    id: 'm4',
    title: 'Beef & Broccoli Stir Fry',
    matchPercentage: 81,
    usedIngredientsCount: 7,
    extraIngredientsRemaining: 3,
    tags: [
      { name: 'Steak', icon: '🥩' },
      { name: 'Broccoli', icon: '🥦' },
      { name: 'Soy Sauce', icon: '🍶' },
      { name: 'Garlic', icon: '🧄' },
      { name: 'Ginger', icon: '🫚' },
      { name: 'Brown Sugar', icon: '🟤' },
      { name: 'White Rice', icon: '🍚' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?q=80&w=300&auto=format&fit=crop',
  },
  {
    id: 'm5',
    title: 'Sheet Pan Lemon Salmon',
    matchPercentage: 79,
    usedIngredientsCount: 6,
    extraIngredientsRemaining: 2,
    tags: [
      { name: 'Salmon', icon: '🐟' },
      { name: 'Lemons', icon: '🍋' },
      { name: 'Zucchini', icon: '🥒' },
      { name: 'Bell Peppers', icon: '🫑' },
      { name: 'Olive Oil', icon: '🫒' },
      { name: 'Garlic', icon: '🧄' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=300&auto=format&fit=crop',
  },
  {
    id: 'm6',
    title: 'Black Bean & Sweet Potato Tacos',
    matchPercentage: 77,
    usedIngredientsCount: 7,
    extraIngredientsRemaining: 3,
    tags: [
      { name: 'Black Beans', icon: '🫘' },
      { name: 'Sweet Potatoes', icon: '🍠' },
      { name: 'Tortillas', icon: '🫓' },
      { name: 'Avocado', icon: '🥑' },
      { name: 'Cumin', icon: '🟡' },
      { name: 'Limes', icon: '🍋' },
      { name: 'Cilantro', icon: '🌿' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?q=80&w=300&auto=format&fit=crop',
  },
  {
    id: 'm7',
    title: 'Weeknight Turkey Chili',
    matchPercentage: 75,
    usedIngredientsCount: 8,
    extraIngredientsRemaining: 4,
    tags: [
      { name: 'Ground Turkey', icon: '🦃' },
      { name: 'Kidney Beans', icon: '🫘' },
      { name: 'Canned Tomatoes', icon: '🥫' },
      { name: 'Onions', icon: '🧅' },
      { name: 'Chili Powder', icon: '🌶️' },
      { name: 'Cumin', icon: '🟡' },
      { name: 'Bell Peppers', icon: '🫑' },
      { name: 'Garlic', icon: '🧄' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=300&auto=format&fit=crop',
  },
  {
    id: 'm8',
    title: 'Garlic Butter Shrimp Scampi',
    matchPercentage: 73,
    usedIngredientsCount: 6,
    extraIngredientsRemaining: 2,
    tags: [
      { name: 'Shrimp', icon: '🍤' },
      { name: 'Spaghetti', icon: '🍝' },
      { name: 'Butter', icon: '🧈' },
      { name: 'Garlic', icon: '🧄' },
      { name: 'Lemons', icon: '🍋' },
      { name: 'Parsley', icon: '🌿' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?q=80&w=300&auto=format&fit=crop',
  },
  {
    id: 'm9',
    title: 'Crispy Chickpea Power Bowl',
    matchPercentage: 71,
    usedIngredientsCount: 7,
    extraIngredientsRemaining: 3,
    tags: [
      { name: 'Chickpeas', icon: '🫘' },
      { name: 'Quinoa', icon: '🌾' },
      { name: 'Kale', icon: '🥬' },
      { name: 'Cherry Tomatoes', icon: '🍅' },
      { name: 'Tahini', icon: '🫙' },
      { name: 'Olive Oil', icon: '🫒' },
      { name: 'Paprika', icon: '🌶️' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=300&auto=format&fit=crop',
  },
  {
    id: 'm10',
    title: 'Loaded Breakfast Scramble',
    matchPercentage: 70,
    usedIngredientsCount: 6,
    extraIngredientsRemaining: 2,
    tags: [
      { name: 'Eggs', icon: '🥚' },
      { name: 'Bacon', icon: '🥓' },
      { name: 'Cheddar Cheese', icon: '🧀' },
      { name: 'Bell Peppers', icon: '🫑' },
      { name: 'Onions', icon: '🧅' },
      { name: 'Butter', icon: '🧈' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=300&auto=format&fit=crop',
  },
];
 
