import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/Colors';

export const homeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  topDiagonalBackground: {
    position: 'absolute',
    top: -340,
    right: 0,
    width: '100%',
    height: 390,
    backgroundColor: COLORS.darkNavy,
    transform: [{ skewY: '20deg' }],
    borderBottomColor: COLORS.goldYellow,
    borderBottomWidth: 8,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 40,
  },
  headerContainer: {
    marginTop: 10,
    marginBottom: 24,
  },
  greetingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  waveIconContainer: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: COLORS.cardWhite,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  waveEmoji: {
    fontSize: 22,
  },
  greetingTextContainer: {
    flexDirection: 'column',
  },
  greetingTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.textDark,
  },
  greetingSubtitle: {
    fontSize: 13,
    color: COLORS.textMuted,
  },
  brandLogo: {
    fontSize: 42,
    fontWeight: '800',
    color: COLORS.darkGold,
    fontFamily: 'PlayfairDisplay_600SemiBold',
    letterSpacing: -0.5,
  },
  heroCard: {
    backgroundColor: COLORS.darkNavy,
    borderRadius: 28,
    paddingVertical: 28,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginBottom: 28,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  clocheContainer: {
    marginBottom: 12,
  },
  heroTitle: {
    color: COLORS.cardWhite,
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
  },
  heroTitleHighlight: {
    color: COLORS.cardWhite,
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 6,
  },
  heroSubtitle: {
    color: '#9CA3AF',
    fontSize: 13,
    marginBottom: 20,
    textAlign: 'center',
  },
  heroButton: {
    backgroundColor: COLORS.goldYellow,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingLeft: 28,
    paddingRight: 8,
    borderRadius: 30,
  },
  heroButtonText: {
    color: COLORS.textDark,
    fontWeight: '700',
    fontSize: 15,
    marginRight: 12,
  },
  heroButtonIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.darkNavy,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionHeader: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: COLORS.textDark,
    fontFamily: 'serif',
  },
  sparkleEmoji: {
    fontSize: 20,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: COLORS.textMuted,
    marginTop: 2,
  },
  decidersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  orDividerText: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.darkNavy,
    marginHorizontal: 8,
  },
  deciderCard: {
    flex: 1,
    borderRadius: 20,
    paddingVertical: 24,
    paddingHorizontal: 14,
    alignItems: 'center',
    minHeight: 210,
    justifyContent: 'space-between',
  },
  deciderIconContainer: {
    marginTop: 4,
    marginBottom: 12,
  },
  deciderTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textDark,
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 16,
  },
  deciderArrowCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
