import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/Colors';

export const mealCardStyles = StyleSheet.create({
  mealsContainerWrapper: {
    flex: 1,
    paddingHorizontal: 20,
    backgroundColor: COLORS.lightBlueBg,
  },
  mealsHeaderContainer: {
    position: 'relative',
    paddingTop: 45,
    paddingBottom: 20,
    alignItems: 'flex-start',
    width: '100%',
  },
  closeViewCrossIcon: {
    position: 'absolute',
    top: 20,
    right: 5,
    padding: 6,
    backgroundColor: 'rgba(46, 64, 83, 0.05)',
    borderRadius: 20,
  },
  mealsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  headerSparkleIcon: {
    fontSize: 22,
    marginRight: 8,
  },
  mealsMainHeadingTitle: {
    fontFamily: 'PlayfairDisplay_600SemiBold',
    fontSize: 28,
    color: COLORS.darkNavy,
  },
  mealsSubheadingText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    color: '#566573',
    lineHeight: 18,
    marginBottom: 4,
  },
  mealsHighlightWarning: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    color: COLORS.darkGold,
  },
  mealsCardsContainerList: {
    marginTop: 10,
  },
  mealDisplayCardLayout: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    borderRadius: 18,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#EAECEE',
    shadowColor: COLORS.darkNavy,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  mealCardThumbnailPhoto: {
    width: 100,
    height: 105,
    borderRadius: 14,
    backgroundColor: '#EAEDED',
  },
  mealCardRightContentSection: {
    flex: 1,
    paddingLeft: 14,
    justifyContent: 'space-between',
  },
  mealTitleRowGroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  mealCardHeadingNameText: {
    fontFamily: 'PlayfairDisplay_600SemiBold',
    fontSize: 17,
    color: COLORS.darkNavy,
    flex: 1,
    paddingRight: 6,
    lineHeight: 20,
  },
  percentageIndicatorWrapper: {
    alignItems: 'center',
    minWidth: 44,
  },
  circularDataRingBorder: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 2.5,
    borderColor: '#F4D03F', // Yellow radial outline border matching design
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  ringPercentageText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 11,
    color: COLORS.darkNavy,
  },
  matchSubLabelBadgeText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 10,
    color: '#7F8C8D',
    marginTop: 2,
  },
  ingredientChipsContainerRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 6,
  },
  singleChipBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF9E7',
    borderWidth: 1,
    borderColor: '#F9E79F',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginRight: 6,
    marginBottom: 4,
  },
  chipPillLabelText: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 11,
    color: COLORS.darkNavy,
  },
  plusMoreRemainingText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 11,
    color: '#7F8C8D',
    marginTop: 6,
    marginBottom: 4,
  },
  usesIngredientsFooterLabelCount: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    color: '#566573',
    marginTop: 2,
  },
  mealsFooterActionsLayout: {
    marginTop: 15,
    alignItems: 'center',
    paddingBottom: 50,
  },
  seeFullListOutlineButton: {
    borderWidth: 1.5,
    borderColor: '#B49221',
    borderRadius: 10,
    width: '100%',
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    marginBottom: 16,
  },
  seeFullListTextBtnStyles: {
    fontFamily: 'Inter_700Bold',
    fontSize: 14,
    color: COLORS.darkNavy,
  },
  goBackTextLinkAction: {
    paddingVertical: 6,
  },
  goBackToPantryLinkText: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 13,
    color: COLORS.darkNavy,
    textDecorationLine: 'underline',
  },
  imageContainer: {
    width: 100,
    height: 105,
    borderRadius: 14,
    backgroundColor: '#EAEDED', // Gray fallback background color while loading or if blank
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  }
});